[package]
name = "m3u-filter"
version = "0.9.10"
edition = "2018"

[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
regex = "1"
clap = { version = "4", features = ["derive"] }
url = "2"
reqwest = { version = "0", features = ["blocking", "json"] }
chrono = "0.4"
actix-web = "4.2"
actix-server = "2.1"
actix-files = "0"
actix-cors = "0"
futures = "0.3"
path-absolutize = "3.0.14"
pest = "2.5.3"
pest_derive = "2.5.3"
enum-iterator = "1.2.0"
unidecode = "0"
petgraph = "0"
openssl = { version = "*", features = ["vendored"] } #https://docs.rs/openssl/0.10.34/openssl/#vendored
