api: { host: 127.0.0.1, port: 8901, web_root: /home/m3u-filter/web }
working_dir: /home/m3u-filter/data
sources:
  - input: { persist: 'playlist_1_{}.m3u', url: 'http://myserver.net/playlist.m3u' }
    targets:
      - filename: playlist_1.m3u
        type: M3u
        filter: 'Group ~ "^DE\s.*" OR Group ~ "TR\s.*" OR Group ~ "TF1.*"'
        options: { ignore_logo: true }
        rename:
          - { field: Group, new_name: 1. DE$1, pattern: ^DE(.*) }
        sort: { order: Asc }
        mapping:
          - France TNT
          - France Premium
          - Belgique
          - Suisse
          - Canada
      - filename: playlist_strm
        type: Strm
        filter: 'Group ~ "^tv-shows.*"'
        options: { ignore_logo: true, cleanup: true, underscore_whitespace: false, kodi_style: true }
        rename:
          - { field: Group, new_name: 1. DE$1, pattern: ^DE(.*) }
        sort: { order: Asc }
