api:
  host: 127.0.0.1
  port: 8901
  web_root: ./web
input:
  url: http://myserver.net/playlist.m3u
  persist: ./playlist_{}.m3u
targets:
  - filename: playlist_1.m3u
    filter:
        mode: Include
        rules:
          - field: Group
            pattern: ^DE\s.*
          - field: Group
            pattern: ^AU\s.*
    rename:
      - field: Group
        pattern: ^DE(.*)
        new_name: 1. DE$1
