api: { host: 127.0.0.1, port: 8901, web_root: /home/m3u-filter/web }
threads: 0
working_dir: /home/m3u-filter/data
# sec  min   hour   day of month   month   day of week   year
schedule: "0  0  8,12,16,20,22,1  *  *  *  *"
video_suffix:
  - .mkv
  - .mp4
  - .avi
templates:
  - name: DE_CHAN
    value: >-
      Group ~ "(?i)^.DE.*Serien.*" OR
      Group ~ "(?i)^.TR.*Filme.*" OR
      Group ~ "(?i)^.TR.*Live.*"
  - name: FR_CHAN
    value: Group ~ "^.FR..*"
  - name: ALL_CHAN
    value: >-
      !DE_CHAN! OR
      !FR_CHAN!
sources:
  - input:
      enabled: true
      type: xtream
      headers:
        User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        Accept: application/json
        Accept-Encoding: gzip
      url: 'http://localhost:8080'
      username: test
      password: test
    targets:
      - name: pl1
        publish: true
        filename: playlist_1.m3u
        type: m3u
        filter: '!ALL_CHAN!'
        options: { ignore_logo: true }
        rename:
          - { field: group, new_name: 1. DE$1, pattern: ^DE(.*) }
        sort:
          groups:
            order: asc
        mapping:
          - France TNT
          - France Premium
          - Belgique
          - Suisse
          - Canada
      - filename: playlist_strm
        type: strm
        filter: 'Group ~ "^tv-shows.*"'
        options: { ignore_logo: true, cleanup: true, underscore_whitespace: false, kodi_style: true }
        rename:
          - { field: group, new_name: 1. DE$1, pattern: ^DE(.*) }
        sort:
          groups:
            order: asc
