version: '3'
services:
  m3u-filter:
    container_name: m3u-filter
    image: m3u-filter:latest
    working_dir: /
    volumes:
      - ./data:/data
      # - ./config.yml:/config.yml
      # - ./api-proxy.yml:/api-proxy.yml
      # - ./mapping.yml:/mapping.yml
    environment:
      - TZ=Europe/Paris
    ports:
      - "8901:8901"
    restart: unless-stopped
